version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up -d
      - run: sleep 60
      - run: docker exec -it project_flower-python_1 python2 services/tests.py
